Issue1437 2147 tim ser loa
lbl-srg/modelica-buildings pull request #2150
Opened 2020-09-21 18:40 UTC by JayHuLBL

This closes #2147. 

- [x] corrected instantiation of conditional blocks so when `have_watHea` or `have_watCoo` becomes false, disabling corresponded blocks.

2020-10-07 21:24 UTC, AntoineGautier requested changes
I agree with the modifications made but I would like to further discuss the modeling intent before merging, see https://github.com/lbl-srg/modelica-buildings/issues/2147#issuecomment-705192554

2020-10-08 17:51 UTC, AntoineGautier approved these changes

2020-10-08 17:55 UTC, AntoineGautier commented
@JayHuLBL I think we can merge this: does that seem good to you? But I would not close the issue #2147 until we discuss the shortcomings described in https://github.com/lbl-srg/modelica-buildings/issues/2147#issuecomment-705192554 with the rest of the team.

2020-10-08 18:28 UTC, JayHuLBL commented
@AntoineGautier I agree with the changes and keep the issue open.

2020-10-08 18:29 UTC, merged