Restructure DHC package
lbl-srg/modelica-buildings pull request #2826
Opened 2021-12-20 06:48 UTC by bravache

This PR reorganize the content of `Buildings.Experimental.DHC` and closes #2825 .

Steps used for refactoring:

1. The package was manually edited to replace all relative class references with absolute paths
2. Folders that did not have `package.mo` file were removed
3. The BuildingsPy script below was ran
4. Obsolete package and folders were deleted
5. Documentation of new packages was added.

Refactor script:

---

```
# Script to refactor DHC package with revised structure
# November 8, 2021
# Kathryn Hinkelman, kathryn.hinkelman@colorado.edu

import buildingspy.development.refactor as r
path = "Buildings.Experimental.DHC." # Path header that does not change

###### Plants ######
# Rename package
r.move_class(path+"CentralPlants",path+"Plants")
# Create missing directories
r.create_modelica_package("Buildings/Experimental/DHC/Plants/Heating")
r.create_modelica_package("Buildings/Experimental/DHC/Plants/Reservoir")
# Relocate models from Examples.Combined.CentralPlants to Plants.Combined
r.move_class(path+"Examples.Combined.Generation5.CentralPlants.SewageHeatRecovery",path+"Plants.Heating.SewageHeatRecovery")
r.move_class(path+"Examples.Combined.Generation5.ThermalStorages.BoreField",path+"Plants.Reservoir.BoreField")
# Rename Buildings.Experimental.DHC.Plants.Cooling.Plant
r.move_class(path+"Plants.Cooling.Plant",path+"Plants.Cooling.ElectricChillerParallel")
r.move_class(path+"Plants.Cooling.Examples.Plant",path+"Plants.Cooling.Examples.ElectricChillerParallel")

###### EnergyTransferStations ######
# Move all content from subpackage "Generation5" to "Combined"
r.move_class(path+"EnergyTransferStations.Combined.Generation5.ChillerBorefield",path+"EnergyTransferStations.Combined.ChillerBorefield")
r.move_class(path+"EnergyTransferStations.Combined.Generation5.HeatPumpHeatExchanger",path+"EnergyTransferStations.Combined.HeatPumpHeatExchanger")
r.move_class(path+"EnergyTransferStations.Combined.Generation5.Controls",path+"EnergyTransferStations.Combined.Controls")
r.move_class(path+"EnergyTransferStations.Combined.Generation5.Subsystems",path+"EnergyTransferStations.Combined.Subsystems")
r.move_class(path+"EnergyTransferStations.Combined.Generation5.Examples",path+"EnergyTransferStations.Combined.Examples")
r.move_class(path+"EnergyTransferStations.Combined.Generation5.Validation",path+"EnergyTransferStations.Combined.Validation")
r.move_class(path+"EnergyTransferStations.Combined.Generation5.BaseClasses",path+"EnergyTransferStations.Combined.BaseClasses")

###### Loads ######
# Relocate models (recursively) from Examples.Combined.Loads to Loads.Combined
r.move_class(path+"Examples.Combined.Generation5.Loads",path+"Loads.Combined")
r.move_class(path+"Loads.FlowDistribution",path+"Loads.BaseClasses.FlowDistribution")
r.move_class(path+"Loads.SimpleRoomODE",path+"Loads.BaseClasses.SimpleRoomODE")
r.move_class(path+"Loads.Controls",path+"Loads.BaseClasses.Controls")
r.move_class(path+"Loads.Types",path+"Loads.BaseClasses.Types")
r.move_class(path+"Loads.Examples",path+"Loads.BaseClasses.Examples")
r.move_class(path+"Loads.Validation.BenchmarkFlowDistribution1",path+"Loads.BaseClasses.Validation.BenchmarkFlowDistribution1")
r.move_class(path+"Loads.Validation.BenchmarkFlowDistribution2",path+"Loads.BaseClasses.Validation.BenchmarkFlowDistribution2")	# Should this be the Network.Dist* example/validation model?
r.move_class(path+"Loads.Validation.FlowDistributionPumpControl",path+"Loads.BaseClasses.Validation.FlowDistributionPumpControl")
r.move_class(path+"Loads.Validation.SimpleRoomODE",path+"Loads.BaseClasses.Validation.SimpleRoomODE")
r.move_class(path+"Loads.Validation.TerminalUnitScaling",path+"Loads.BaseClasses.Validation.TerminalUnitScaling")
r.move_class(path+"Loads.Validation.BaseClasses.FanCoil2PipeCooling",path+"Loads.BaseClasses.Validation.BaseClasses.FanCoil2PipeCooling")
r.move_class(path+"Loads.Validation.BaseClasses.FanCoil2PipeHeating",path+"Loads.BaseClasses.Validation.BaseClasses.FanCoil2PipeHeating")
r.move_class(path+"Loads.Validation.BaseClasses.FanCoil2PipeHeatingValve",path+"Loads.BaseClasses.Validation.BaseClasses.FanCoil2PipeHeatingValve")

###### Networks ######
r.move_class(path+"Examples.Combined.Generation5.Networks.UnidirectionalParallel",path+"Networks.Combined.UnidirectionalParallel")
r.move_class(path+"Examples.Combined.Generation5.Networks.UnidirectionalSeries",path+"Networks.Combined.UnidirectionalSeries")
r.move_class(path+"Examples.Combined.Generation5.Networks.BaseClasses.ConnectionParallelAutosize",path+"Networks.Combined.BaseClasses.ConnectionParallelAutosize")
r.move_class(path+"Examples.Combined.Generation5.Networks.BaseClasses.ConnectionParallelStandard",path+"Networks.Combined.BaseClasses.ConnectionParallelStandard")
r.move_class(path+"Examples.Combined.Generation5.Networks.BaseClasses.ConnectionSeriesAutosize",path+"Networks.Combined.BaseClasses.ConnectionSeriesAutosize")
r.move_class(path+"Examples.Combined.Generation5.Networks.BaseClasses.ConnectionSeriesStandard",path+"Networks.Combined.BaseClasses.ConnectionSeriesStandard")
r.move_class(path+"Examples.Combined.Generation5.Networks.BaseClasses.PipeAutosize",path+"Networks.Combined.BaseClasses.PipeAutosize")
r.move_class(path+"Examples.Combined.Generation5.Networks.BaseClasses.PipeStandard",path+"Networks.Combined.BaseClasses.PipeStandard")
r.move_class(path+"Loads.Validation.BaseClasses.Connection2Pipe",path+"Networks.Connection2Pipe")
r.move_class(path+"Loads.Validation.BaseClasses.Distribution2Pipe",path+"Networks.Distribution2Pipe")

###### Examples ######
r.move_class(path+"Examples.Combined.Generation5.Examples.ParallelConstantFlow",path+"Examples.Combined.ParallelConstantFlow")
r.move_class(path+"Examples.Combined.Generation5.Examples.SeriesConstantFlow",path+"Examples.Combined.SeriesConstantFlow")
r.move_class(path+"Examples.Combined.Generation5.Examples.SeriesVariableFlow",path+"Examples.Combined.SeriesVariableFlow")
r.move_class(path+"Examples.Combined.Generation5.Examples.BaseClasses",path+"Examples.Combined.BaseClasses")
r.move_class(path+"Examples.Combined.Generation5.Data.DesignDataParallel",path+"Examples.Combined.BaseClasses.DesignDataParallel")
r.move_class(path+"Examples.Combined.Generation5.Data.DesignDataSeries",path+"Examples.Combined.BaseClasses.DesignDataSeries")
```

2021-12-20 06:50 UTC, bravache commented
@khinkelman Katy this is the refactoring pull request.
@mwetter Please check the structure of the DHC package. It was restructured following the discussion with CU Boulder, and the structure we landed on is available here: https://docs.google.com/document/d/12GaIloYaMds4USyhZt1W_s2hB2W2_GWR

2021-12-22 14:05 UTC, mwetter requested changes
@bravache :

This is almost ready to merge. The following needs to be corrected first:
1. Exporting the html documentation gives
```
Error: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.Generation5" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.Examples
Error: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.Generation5" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.Validation
Error: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.Generation5" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.BaseClasses
Error: Can not resolve link "modelica://Buildings.Experimental.DHC.Examples.Combined.Generation5.Examples" in Buildings.Experimental.DHC.Examples.Combined.BaseClasses```
Also, the OCT unit tests fail because `Resources/Scripts/BuildingsPy/conf.json` is not updated. (BuildingsPy does not update this file, as the file has been added after the merge script was developed, this should at some point be fixed.) Can you please update this file. Then it is ready to merge.
```
2. The OPTIMICA unit tests fail because `Resources/Scripts/BuildingsPy/conf.json` is not updated. (BuildingsPy does not update this file, as the file has been added after the merge script was developed, this should at some point be fixed.)

Then it is ready to merge.

2021-12-22 18:49 UTC, bravache commented
@mwetter I've updated the link. Ready to merge after the tests!

2021-12-23 15:12 UTC, mwetter approved these changes

2021-12-23 15:13 UTC, merged