Updated CDL block addParameter
lbl-srg/modelica-buildings pull request #2877
Opened 2022-02-03 22:51 UTC by JayHuLBL

This closes #2876.

- [x] moved existing `CDL.Continuous.AddParameter` to `Obsolete`
- [x] created new `CDL.Continuous.AddParameter` so there is no input gain factor. It will be the same as Eikon microblock
- [x] created new block 'CDL.Integers.AddParameter`
- [x] updated the affected blocks in library
- [x] updated conversion script and the release note

2022-02-04 21:42 UTC, JayHuLBL commented
@mwetter It's ready for review.

2022-02-07 12:29 UTC, mwetter requested changes
The file `Buildings/package.mo` has a merge conflict that needs to be resolved. See inline comment.

2022-02-07 12:29 UTC, mwetter commented on Buildings/package.mo
> +<<<<<<< HEAD
These merge conflicts needs to be resolved.

2022-02-07 18:48 UTC, mwetter approved these changes

2022-02-08 01:48 UTC, merged