Added hysteresis to CDL.Integer blocks
lbl-srg/modelica-buildings pull request #2979
Opened 2022-04-27 22:32 UTC by JayHuLBL

This closes #2978. Added hysteresis to following blocks:
- [x] `Buildings.Controls.OBC.CDL.Integers.Greater`
- [x] `Buildings.Controls.OBC.CDL.Integers.GreaterThreshold`
- [x] `Buildings.Controls.OBC.CDL.Integers.Less`
- [x] `Buildings.Controls.OBC.CDL.Integers.LessThreshold`

2022-04-27 22:53 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Integers/Greater.mo
> +To disable hysteresis, set <code>h=0</code>.
This needs to be deleted as this is not applicable to Integer-valued signals.

2022-04-27 22:55 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Integers/Greater.mo
> +  final parameter Boolean have_hysteresis=h >= 1E-10
`h` is an `Integer`, so just check for `h > 0`. (I am surprised that this gives not a warning.) Please also change in the other new blocks.

2022-04-27 22:56 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Integers/GreaterThreshold.mo
> +  final parameter Boolean have_hysteresis=h >= 1E-10
See above, just check for `>0`.

2022-04-27 22:56 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Integers/GreaterThreshold.mo
> +To disable hysteresis, set <code>h=0</code>.
Remove, see above

2022-04-27 23:09 UTC, JayHuLBL commented
@mwetter The documentation has been updated. Also, the check of `have_hysteresis` have been changed.

2022-04-27 23:19 UTC, mwetter requested changes
See inline comments. 
Also, the blocks `Integer.{GreaterEqual,GreaterEqualThreshold}` and `Integer.{LessEqual,LessEqualThreshold}` have no hysteresis. 
I think we should also add it for them so that all inequality comparison, whether strict or weak, have the same parameters, no?

2022-05-03 22:03 UTC, mwetter commented
This won't be merged as it add non-needed complexity.

2022-05-03 22:03 UTC, closed without merging