Issue3103 sequence binary
lbl-srg/modelica-buildings pull request #3112
Opened 2022-09-19 16:45 UTC by JayHuLBL

This closes #3103.

2022-09-21 15:51 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Integers/SequenceBinary.mo
> +  parameter Real minStaOn(
Can you explain the behavior without ON and OFF as this block (and CDL) has no notion of ON or OFF.

2022-09-21 16:00 UTC, mwetter requested changes
See inline comments

2022-09-21 16:00 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Integers/SequenceBinary.mo
> +  Buildings.Controls.OBC.CDL.Continuous.GreaterThreshold greThr[nSta](
Do we really need `nSta` instances of this block? Why not using one `Greater` and set the input to avoid zero crossing functions.

2023-03-01 18:22 UTC, JayHuLBL commented
@mwetter It's ready for your review.

2023-03-01 23:09 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Integers/Validation/SequenceBinary.mo
> +    "Total number of enabled stages, with zero stage ON-OFF holding time"
Describe without ON-OFF

2023-03-01 23:14 UTC, mwetter approved these changes
The block looks good. Please see the change in parameter name to make it consistent with other parameters

2023-03-02 23:59 UTC, mwetter commented
Todo: 
- [ ] Change name from `SequenceBinary` to `Stage`.
- [ ] Remove mentioning of "ON" and "OFF" as these are not terms used in CDL.
Then it is ready to be merged.

2023-03-03 00:32 UTC, JayHuLBL commented
@mwetter 
- [x] changed the block name to `Stage`
- [x] removed mentioning of "ON"/"OFF"

2023-03-03 23:15 UTC, mwetter approved these changes

2023-03-06 17:14 UTC, merged