Added boolean and integer extractor
lbl-srg/modelica-buildings pull request #3128
Opened 2022-10-05 23:00 UTC by JayHuLBL

This closes #3125.

2022-10-06 16:26 UTC, mwetter requested changes
See inline comments, lets discuss the implementation and documentation.

2022-10-07 17:26 UTC, JayHuLBL commented on Buildings/Controls/OBC/CDL/Routing/BooleanExtractor.mo
> +  y = sum(if temp[i] then 1 else 0 for i in 1:nin) == 1;
If we put the `y = ` within the `when` clause, it will not be translated, with singularity error.

2022-10-07 17:41 UTC, JayHuLBL commented on Buildings/Controls/OBC/CDL/Routing/BooleanExtractSignal.mo
> +
Thanks! I will add the assertion.

2022-10-07 17:41 UTC, JayHuLBL commented on Buildings/Controls/OBC/CDL/Routing/BooleanExtractor.mo
> +    "Index may be out of range";
Agree. I think we don't need to have the `allowOutOfRange` parameter. By issuing an assertion with warning and return the `outOfRangeValue` should be enough.

In `RealExtractor`, it does have the `allowOutOfRange` value:
- when the `allowOutOfRange=false` and the input index is out of range, the output will be `0`; (should a warning be issued?)
- when the `allowOutOfRange=true` and the input index is out of range, the output will be `outOfRangeValue`, which is `1e10` in default.

2022-10-07 21:52 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Routing/BooleanExtractor.mo
> +  y = sum(if temp[i] then 1 else 0 for i in 1:nin) == 1;
This seems to work:
```modelica
block BooleanExtractor
  "Extract scalar signal out of signal vector dependent on Integer input index"
  parameter Integer nin(min=1)=1
    "Number of inputs";
  Interfaces.IntegerInput index(
    final min=1,
    final max=nin)
    "Index of input vector element to be extracted out"
    annotation (Placement(transformation(origin={0,-120},extent={{-20,-20},{20,20}},rotation=90)));
  Interfaces.BooleanInput u[nin]
    "Connector of Boolean input signals"
    annotation (Placement(transformation(extent={{-140,-20},{-100,20}})));
  Interfaces.BooleanOutput y
    "Connector of Boolean output signal"
    annotation (Placement(transformation(extent={{100,-20},{140,20}})));

equation 
  y = u[min(nin, max(1, index))];
end BooleanExtractor;

```

2022-10-10 16:24 UTC, mwetter commented on Buildings/Controls/OBC/CDL/Routing/BooleanExtractor.mo
> +    "Index may be out of range";
I think if the index is out of range, we should issue an assertion with level set to warning, and output the element with the nearest valid index, which is what `u[min(nin, max(1, index))];` returns

2022-10-11 16:45 UTC, JayHuLBL commented
@mwetter in current implementation, it will issue the warning when the extract index is out of range and the output value will be the nearest valid index.

2022-10-12 22:01 UTC, JayHuLBL commented
@mwetter It will be ready for your review when the CI tests passed.

2022-10-13 18:37 UTC, JayHuLBL commented
@mwetter The last commit has some minor changes to the text. I have tested locally the html syntax and the file format.

It's ready for your review.

2022-10-14 14:02 UTC, mwetter requested changes
@JayHuLBL : Please see inline comments for initial feedback on this revised version that is not ready for release.

2022-10-17 05:18 UTC, JayHuLBL commented on Buildings/Controls/OBC/CDL/Routing/BooleanExtractSignal.mo
> +    AssertionLevel.error);
Addressed.

2022-10-17 22:41 UTC, JayHuLBL commented on Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_9_to_10.0.0.mos
> +convertModifiers("Buildings.Controls.OBC.CDL.Routing.RealExtractor",
corrected.

2022-10-18 01:35 UTC, mwetter approved these changes

2022-10-18 05:46 UTC, merged