Issue3438 d xdehumidifier
lbl-srg/modelica-buildings pull request #3440
Opened 2023-06-22 11:54 UTC by karthikeyad-pnnl

2023-06-23 14:48 UTC, karthikeyad-pnnl commented
@mwetter @JayHuLBL I am submitting this PR to merge the DX dehumidifier component model into the Buildings library. This is a fairly simple model with dependencies on classes already in the master branch. Please review the code as well as the proposed package structure for the new addition.
Thanks!
-Karthik

2023-06-23 23:51 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/DXDehumidifier.mo
> +  parameter Modelica.Units.SI.PressureDifference dp_nominal
add `displayUnit="Pa"` attribute.

2023-06-23 23:53 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/DXDehumidifier.mo
> +  parameter Modelica.Units.SI.MassFlowRate m_flow_nominal
group the parameter to group `Nominal condition`.

2023-06-23 23:56 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/DXDehumidifier.mo
> +    annotation (choicesAllMatching=true,
make sure the parameters in the same group consequently together. 

For example here, the parameter `V_flow_nominal` is in group `Nominal condition`, the parameter `addPowerToMedium` is not grouped, and then again, the parameter `eneFac_nominal` is in group `Nominal condition` again. It should be avoided.

2023-06-23 23:58 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/DXDehumidifier.mo
> +  Modelica.Blocks.Interfaces.RealOutput T(
best should make sure the connectors are in the same sections of the code. The ideal order would be parameter section, connector sections, and other instances section.

2023-06-23 23:59 UTC, JayHuLBL requested changes
@karthikeyad-pnnl Please see inline comments.

Also, see following errors:
```
jianjunhu@ubuntu:~/GitFolder/karthikeyad-pnnl/modelica-buildings/Buildings$ ../bin/verifyFiles.py 
*** Error:  File 'Fluid/Humidifiers/Examples/DXDehumidifier.mo' contains invalid string 'Algorithm='.
*** Error:  File 'Fluid/Humidifiers/Examples/DXDehumidifier.mo' contains invalid string '__Dymola_Algorithm'.
*** Error:  File 'Fluid/Humidifiers/Validation/DXDehumidifier.mo' contains invalid string 'Algorithm='.
*** Error:  File 'Fluid/Humidifiers/Validation/DXDehumidifier.mo' contains invalid string '__Dymola_Algorithm'.
*** Terminating due to found errors in examined files.

jianjunhu@ubuntu:~/GitFolder/karthikeyad-pnnl/modelica-buildings/Buildings$ ../bin/validateHTML.py 
The following malformed html syntax has been found:
[-- ./Fluid/Humidifiers/DXDehumidifier.mo ]
line 69 column 1 - Warning: inserting implicit <p>
line 65 column 1 - Warning: trimming empty <p>
line 69 column 1 - Warning: trimming empty <p>
```

2023-07-24 18:24 UTC, karthikeyad-pnnl commented
@JayHuLBL We have addressed the comments above. Please review it when you get a chance. Thanks!

2023-07-28 22:53 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/DXDehumidifier.mo
> +    Icon(coordinateSystem(extent={{-100,-80},{100,80}}), graphics={
change the `extent={{-100,-80},{100,80}}` to `extent={{-100,-100},{100,100}}`. So the Icon is consistent with other humidifiers like `Humidifier_u`.

2023-07-28 22:56 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/Data/Generic.mo
> +          fontSize=16,
remove the specification of the `fontSize`.

2023-07-28 22:56 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/Data/Generic.mo
> +          fontSize=16)}));
remove the specification of the `fontSize`.

2023-07-28 23:01 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/Examples/Data/DXDehumidifier.mo
> +    Icon(graphics={
There is no need to have the `Icon()` annotation, as the class extents the `Buildings.Fluid.Humidifiers.Data.Generic`.

2023-07-28 23:05 UTC, JayHuLBL commented on Buildings/Fluid/Humidifiers/Validation/DXDehumidifier.mo
> +    results.";
Don't change to new line. Always keep the comment in one line.

2023-07-28 23:14 UTC, JayHuLBL requested changes
@karthikeyad-pnnl Please see inline comments.

2023-08-07 21:22 UTC, karthikeyad-pnnl commented
@JayHuLBL: @terrancelu92 has addressed the pending comments. Please review the PR when you get a chance. Thanks!

2023-08-17 23:55 UTC, merged