Multizone AHU controller: Removed measured input, fixed singular issues
lbl-srg/modelica-buildings pull request #3531
Opened 2023-09-20 21:03 UTC by JayHuLBL

This closes #3526.
- [x] removed the measured damper position inputs
- [x] added 2-position relief damper boolean output
- [x] added electric heating coil option
- [x] fixed singular issues

2023-09-22 09:16 UTC, AntoineGautier requested changes
We are getting very close!
I used this script to test ***all*** valid combinations of the controller parameters (this is based on the developments from https://github.com/lbl-srg/modelica-buildings/pull/3528).
https://github.com/AntoineGautier/modelica-buildings/blob/tmp/issue3526_connectors/Buildings/Resources/Scripts/travis/templates/VAVMultiZoneController.py
It turns out that only ***11 %*** of the tested combinations fail to simulate (with a high probability of a recurring pattern that could explain most of them). I am sending the log file to you by email so that you can inspect and debug the faulty ones.

In addition, I have the following comments.

Inside `Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.SetPoints.PlantRequests` the input `uCooCoiSet` is not conditional. The block is still incompatible with the following options.

- No cooling coil
- DX coil

Could we introduce a parameter to specify the type of cooling coil, and adapt the block in a similar manner as with `have_hotWatCoi`?
Also, since we want to cover 3 options for the heating coil (none, HW, electric) and for the cooling coil (none, CHW, DX) I would rather introduce enumerations to describe these options, rather than increasing the number of Boolean parameters, such as `have_hotWatCoi` and `have_eleHeaCoi`. Note also that the implementation currently does not avoid `have_hotWatCoi=true` and `have_eleHeaCoi=true`, which an enumeration would avoid.

2023-09-22 09:20 UTC, AntoineGautier commented
Hi Jianjun

Thanks for the quick feedback and corrections for issue #3526.
Following my review at
https://github.com/lbl-srg/modelica-buildings/pull/3531#pullrequestreview-1639511502,
I
am sending you the log file.

Best
--
Antoine


On Wed, Sep 20, 2023 at 11:03 PM Jianjun Hu ***@***.***>
wrote:

> @JayHuLBL <https://github.com/JayHuLBL> requested your review on: #3531
> <https://github.com/lbl-srg/modelica-buildings/pull/3531> Multizone AHU
> controller: Removed measured input, fixed singular issues.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lbl-srg/modelica-buildings/pull/3531#event-10427736978>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACTVH2UFDBBJCMBRMIW23W3X3NK3XANCNFSM6AAAAAA5AQYQHI>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-09-22 21:13 UTC, JayHuLBL commented
@AntoineGautier I added the new enumeration `Buildings.Controls.OBC.ASHRAE.G36.Types.Coil` that lists coil types. However, it has less items than the one in Template folder `Buildings.Templates.Components.Types.Coil`.

The new enumeration has been applied in MultiZone and single zone VAV controller, and also the terminal unit controllers. Due to the change, I believe the template models also need to update.

2023-09-22 21:39 UTC, AntoineGautier commented
@JayHuLBL Noted. I'll refactor the templates via a commit to the branch `issue3526_connectors` early next week.

2023-09-25 08:08 UTC, AntoineGautier commented on Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Controller.mo
>                  Dialog(group="System and building parameters"));
@JayHuLBL I think 2 distinct enumerations should be introduced: one for heating coils, another one for cooling coils.
The current implementation does not prevent from selecting `cooCoi=Buildings.Controls.OBC.ASHRAE.G36.Types.Coil.ElectricHeating` for example (the simulation of `Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Validation.Controller` actually succeeds with this class modification).
Let me know if this is possible. (I'll wait before refactoring the VAV template.)

2023-09-25 17:01 UTC, JayHuLBL commented
@AntoineGautier I was thinking about having two distinct enumeration, but realized that in `Template` folder, it also uses one enumeration. Will the same issue exist for the template models?
However, it would be relatively easy to make the change to have two enumuerations. Please let me know your thought about the one in `Template` folder.

2023-09-25 17:13 UTC, AntoineGautier commented
The use of the enumeration differs in the Templates package. The enumeration itself is not exposed to the user, but only used "in the background", as a means of type introspection, for example:
```
within Buildings.Templates.Components.Coils;
model ElectricHeating "Modulating electric heating coil"
  extends Buildings.Templates.Components.Interfaces.PartialCoil(
    final typ=Buildings.Templates.Components.Types.Coil.ElectricHeating,
``` 
At the top-level, we use replaceable components with an explicit choices annotation, for example:
```
replaceable Buildings.Templates.Components.Coils.WaterBasedHeating coiHeaPre(...)
    constrainedby Buildings.Templates.Components.Interfaces.PartialCoil(...)
    "Heating coil in preheat position"
    annotation (
    choices(
      choice(
        redeclare replaceable Buildings.Templates.Components.Coils.None coiHeaPre
        "No coil"),
      choice(
        redeclare replaceable Buildings.Templates.Components.Coils.WaterBasedHeating coiHeaPre(
          redeclare final package MediumHeaWat=MediumHeaWat,
          redeclare final Buildings.Templates.Components.Valves.TwoWayModulating val)
        "Hot water coil with two-way valve"),
      choice(
        redeclare replaceable Buildings.Templates.Components.Coils.ElectricHeating coiHeaPre
        "Modulating electric heating coil")),
```
Having enumerations that differ between the packages Controls and Templates is not an issue. (Of course, if we can use the same, this is better, but this is not a requirement.)

2023-09-25 18:38 UTC, JayHuLBL commented
@AntoineGautier I just changed the one enumeration to two enumerations for heating and cooling coil.

2023-09-26 10:13 UTC, AntoineGautier commented
I updated the templates in my last commit.

However, the model `Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.Validation.Controller` fails to compile with the following class modification.
```
conAHU(heaCoi=Buildings.Controls.OBC.ASHRAE.G36.Types.HeatingCoil.Electric)
```

The model `Buildings.Controls.OBC.ASHRAE.G36.TerminalUnits.Reheat.Controller` enables selecting `heaCoi=Buildings.Controls.OBC.ASHRAE.G36.Types.HeatingCoil.None`. This should not be permitted as then it is a cooling-only box that is modeled with `Buildings.Controls.OBC.ASHRAE.G36.TerminalUnits.CoolingOnly`. 
If `choices` annotations are allowed in CDL, you can restrict the choices exposed in the parameter dialog by adding such annotation to the declaration of `parameter Buildings.Controls.OBC.ASHRAE.G36.Types.HeatingCoil heaCoi`. As this is only a UI feature, an assert statement guarding against `heaCoi==Buildings.Controls.OBC.ASHRAE.G36.Types.HeatingCoil.None` is also needed.

2023-10-07 11:59 UTC, AntoineGautier approved these changes

2023-10-07 12:00 UTC, AntoineGautier commented
@JayHuLBL This is ready to merge I believe.

2023-10-09 23:30 UTC, JayHuLBL commented
@mwetter Please let us know if it is ready to merge.

2023-10-16 13:59 UTC, JayHuLBL commented
@mwetter The tests have passed and it is ready for your review.

2023-10-24 17:42 UTC, merged