Add Modelica Tough coupling user guide
lbl-srg/modelica-buildings pull request #3696
Opened 2024-03-11 18:03 UTC by JayHuLBL

2024-03-11 18:18 UTC, JayHuLBL commented
@EttoreZ Would you please take another look at the changes?

2024-03-11 19:54 UTC, EttoreZ commented
Hey @JayHuLBL just two quick comments:

- In the doStep description of the UserGuide. I would comment/remove this line: ` os.system("./writeincon < writeincon.inp")` and uncomment this line ` # write_incon()`, and also remove this line `os.system(" ./readsave < readsave.inp > out.txt")` and uncomment this line `# readsave()`. This is because the Python script now does not rely on the Fortran utility programs anymore.
- The second comment is also related to that. In the diagram where you show the workflow of the Python script, `writeincon` and `readsave` are cited as utility programs. I would change that to Python functions.
Apart from those, everything else looks good to me.

2024-03-11 21:29 UTC, JayHuLBL commented
@EttoreZ Thanks for the comments. I just addressed it. Please double-check.

2024-03-12 00:57 UTC, EttoreZ commented
@JayHuLBL  the changes look good to me.

2024-12-11 18:31 UTC, JayHuLBL commented
@mwetter It's ready for your review.

2024-12-18 16:59 UTC, mwetter requested changes
Please do one more revision.

2025-09-22 17:18 UTC, JayHuLBL commented
@mwetter It's ready for your review.

2025-09-25 22:07 UTC, mwetter requested changes
This is not ready for review.

I started a review but stopped. You need to check it more carefully and revise the writing one more time for clarity.

Also, we can't post binaries with such dependencies that will inadvertently break as Ubuntu is being updated.

Also, earlier comment is still unaddressed.

2025-09-25 22:07 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGHResponse/UsersGuide.mo
> +therefore takes the initial temperature from the Modelica to initialize the object.
It is not clear what "this object" refers to. Do you mean the ground temperature? Are they initialized uniformly, or does TOUGH initialize the ground temperature through its input files?

2025-09-25 22:07 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/UsersGuide.mo
> +The start time is the one stored in the state. The stop time is the current
I don't understand that bullet. `INFILE` is a file, but then the description says time will be updated. Explain this clearer.

2025-09-25 22:07 UTC, mwetter commented on Buildings/Resources/Python-Sources/TOUGH/readsave
This is a binary file. We need to post the source code and the built file.
Also, this implies that the coupling only works on Linux 64 bit, and there are various dependencies.
Moreover, `readsave` and`writeincon` depend on different versions of `libgfortran` (and I don't think version 4 is available on Ubuntu 24.04.
What are these files doing and why are they only in compiled form?

2025-09-25 22:07 UTC, mwetter commented on Buildings/Resources/Images/Fluid/Geothermal/Borefields/TOUGHResponse/workFlow.svg
@JayHuLBL : this is still not addressed.

2025-09-25 22:07 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGHResponse/BaseClasses/PartialBorefieldWithTough.mo
> +thermal response factor.
What does cell-shifting load aggregation and thermal response factor has to do with TOUGH?

2026-01-22 00:26 UTC, JayHuLBL commented on Buildings/Resources/Python-Sources/TOUGH/readsave
The function is now being replaced by the Python function.

2026-03-11 22:18 UTC, JayHuLBL commented
The CI test of the TOUGH coupling example model failed to run, as it uses the Python interface function which now requires Python 3.8. However, current Dymola docker container image does not support Python 3.8, see below comments in master branch:
https://github.com/lbl-srg/modelica-buildings/blob/b45ef02a949be99a1a975e2ae7c7dc3651944c00/Buildings/Resources/Scripts/BuildingsPy/conf.yml#L594

We would be able to run the example models, after merging the PR #4493.

2026-03-24 00:30 UTC, JayHuLBL commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/BaseClasses/GroundResponse.mo
> +  when {terminal()} then
The `terminal()` function is not supported by Optimica 1.66.

The function is also being used in [Buildings.DHC.Loads.HotWater.ThermostaticMixingValve](https://github.com/lbl-srg/modelica-buildings/blob/dc18485a811428470bad3288af1371c771173d82/Buildings/DHC/Loads/HotWater/ThermostaticMixingValve.mo#L236). Running the model `Buildings.DHC.Loads.HotWater.Examples.StorageTankWithExternalHeatExchanger` with Optimica 1.66, we can see
```
In component theMixVal:
    The terminal() operator is not supported, and is currently evaluated to false
```

2026-05-13 21:33 UTC, JayHuLBL commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/BaseClasses/GroundResponse.mo
> +  when {terminal()} then
The coupled simulation requires creating the temporary folder for TOUGH simulation. If the temporary folder cannot be removed after the simulation in CI test, the test will fail. Thus, the `terminal()` is used in the validation model, for deleting the temp folder at the end of the simulation.

The coupled simulation itself does not require the `terminal()` operator.

2026-05-13 21:34 UTC, JayHuLBL commented
@mwetter It will be ready for your review after the CI tests passed.

2026-06-08 17:28 UTC, JayHuLBL commented
- [x] added new icons for the modelica-tough coupling class
- [x] enabled openmodelica simulation
- [x] moved the TOUGH files to data folder
- [x] changed the TOUGH working folder to a temp folder
- [x] used model time block

2026-06-08 17:40 UTC, JayHuLBL commented
@mwetter It's ready for your review.

2026-06-17 13:24 UTC, mwetter requested changes
The file `Buildings/UsersGuide/package.mo` lists all users’ guides of the library. You also need to add the TOUGH users’ guide to that table.

Please also see other inline comments.

2026-06-17 13:24 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/BaseClasses/Validation/GroundResponse.mo
> +    Modelica.Utilities.Files.remove("Resources/Python-Sources/tmp-tou-work");
This needs to be changed as the library folder may be read only if the library is properly installed (such as in `/usr/local`.
Instead, in Tough, get the system dependent tmp folder, and use that instead.

2026-06-17 13:24 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/BaseClasses/GroundResponse.mo
> +    "Current time"
This won't work if the simulation does not start at t=0. See other models where we use the model time. If  Tough internally needs to start at t=0, then it would be better to put this into the Python code as this block does not output the "Current time".

2026-06-17 13:24 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/BaseClasses/Validation/GroundResponse.mo
> +    Modelica.Utilities.Files.remove("Resources/Python-Sources/tmp-tou-work");
This is not correctly addressed: Currently files are written to cwd/tmp-tou-wor where cwd is the current working directory. If there are two borefields, this won’t work as they use the same directory. Instead, use the python mechanism to get a unique name for a temporary directory, and prepend to it tmp-tou-wor. See for example BuildingsPy for how temporary directories are created.

This change also requires you to change the line 
```modelica
Modelica.Utilities.Files.remove(”tmp-tou-wor”);
```

When you change GroundResponse.py, also remove code that is commented out if that code is no longer needed (or if you have a reason for keeping it, add a comment to the file that explains why it is still there).

2026-06-17 13:24 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/BaseClasses/PartialBorefield.mo
> +    annotation (choicesAllMatching=true,Placement(transformation(extent={{-80,-80},{-60,-60}})));
This model uses the instance `borFieDat`, which requires borehole coordinates and soil properties. Neither of them are used in this model. Therefore, this data record should not be used here as users may be confused about having to enter data that end up not being used, and also because TOUGH allows non-uniform soil data which contradicts the soil data entry in borFieDat.
You will need to use a data record that has only those data that are needed by this model

2026-06-17 13:24 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/Examples/Borefield.mo
TOUGH.Examples.Borefields need to be renamed to TOUGH.Examples.Borefield as it is only one borefield.

2026-06-23 19:07 UTC, JayHuLBL commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/BaseClasses/Validation/GroundResponse.mo
> +    Modelica.Utilities.Files.remove("Resources/Python-Sources/tmp-tou-work");
By extending the class `Buildings.Utilities.IO.Python_3_12.Real_Real` to the package and add the string parameter for naming TOUGH working folder would not work, as the `Buildings.Utilities.IO.Python_3_12.Real_Real` hard coded `nStrWri=0, strWri={""}` as below:
```Modelica
    yR = Buildings.Utilities.IO.Python_3_12.Functions.exchange(
      moduleName=moduleName,
      functionName=functionName,
      dblWri=uRWri,
      intWri={0},
      nDblWri=nDblWri,
      nDblRea=nDblRea,
      nIntWri=0,
      nIntRea=0,
      nStrWri=0,
      strWri={""},
      pytObj=pytObj,
      passPythonObject = passPythonObject);
    // Store current value of integral
```
It would be necessary to duplicate the `Real_Real`?

Or, just use the Python mechanism to get the unique name for the temporary directory. The temporary directory will be used for the TOUGH simulation sampling moment, and thus it cannot be deleted by the Python code (and also Modelica). Not sure if the not-deleted temporary directory will cause CI test fail.

2026-06-23 19:32 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/BaseClasses/Validation/GroundResponse.mo
> +    Modelica.Utilities.Files.remove("Resources/Python-Sources/tmp-tou-work");
We should delete the temporary directory after the simulations. You may need to copy `Real_Real` to have an implementation that allows sending a string parameter.

2026-06-23 22:25 UTC, JayHuLBL commented
- [x] renamed example model
- [x] added user guide link to the table of the UserGuide
- [x] corrected the model to allow sampling at begin of any simulation start time
- [x] added borefield data record
- [x] duplicated the python interface model and propagated the parameters for wring string to python

2026-07-16 23:07 UTC, mwetter requested changes
@JayHuLBL : Once the UsersGuide.mo is revised, this is ready to merge.

2026-07-16 23:07 UTC, mwetter commented on Buildings/Fluid/Geothermal/Borefields/TOUGH/UsersGuide.mo
> +    os.system(\"/.../tough3-install/bin/tough3-eos1\")
There is no such code in the python file. 
Update the user guide to reflect the actual implementation.

2026-07-17 22:56 UTC, mwetter approved these changes

2026-07-21 22:41 UTC, mwetter commented
There seems to be a race condition. On my Linux computer, if I run omc in the docker with the command
```bash
for i in {1..20}; do echo "=== Test $i"; ../bin/runUnitTests.py -s Buildings.Fluid.Geothermal.Borefields.TOUGH.BaseClasses.Validation -d -b -t openmodelica --skip-verification || break; done
```
and BuildingsPy 5.2.0, the test fails usually in the first 5 evaluations.

If run outside of the docker, the test works for all 20 runs.

Further tests show that the reason is not `BuildingsPy`:
A test failed in `/tmp/tmp-Buildings-0-nmt8avn4`. Next, running, with omc from the docker, the command
```bash
cd /tmp/tmp-Buildings-0-nmt8avn4
$ omc Buildings.Fluid.Geothermal.Borefields.TOUGH.BaseClasses.Validation.GroundResponse_simulate.mos 
Using docker lbnlblum/ubuntu-2404-omc:1.26.3-1
[/mnt/shared/tmp-Buildings-0-nmt8avn4/Buildings.Fluid.Geothermal.Borefields.TOUGH.BaseClasses.Validation.GroundResponse_simulate.mos:1:17-1:230:writable] Warning: Lexer treating \ as \\, since \[ is not a valid Modelica escape sequence.

... [multiple outputs omitted]

[/mnt/shared/tmp-Buildings-0-nmt8avn4/Buildings.Fluid.Geothermal.Borefields.TOUGH.BaseClasses.Validation.GroundResponse_simulate.mos:1:17-1:585:writable] Warning: Lexer treating \ as \\, since \] is not a valid Modelica escape sequence.

LOG_STDOUT        | warning | simulation_input_xml.c: override variable name not found in model: startTime
LOG_STDOUT        | warning | simulation_input_xml.c: override variable name not found in model: stopTime
LOG_STDOUT        | warning | simulation_input_xml.c: override variable name not found in model: stepSize
LOG_STDOUT        | warning | simulation_input_xml.c: override variable name not found in model: tolerance
LOG_STDOUT        | warning | simulation_input_xml.c: override variable name not found in model: solver
LOG_STDOUT        | warning | simulation_input_xml.c: override variable name not found in model: outputFormat
LOG_STDOUT        | warning | simulation_input_xml.c: override variable name not found in model: variableFilter
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.

Limited backtrace at point of segmentation fault
/lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7613e76c1330]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x326b38)[0x7613e8fabb38]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x1aef3b)[0x7613e8e33f3b]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x32777c)[0x7613e8fac77c]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x329474)[0x7613e8fae474]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x2cf62f)[0x7613e8f5462f]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x43e4)[0x7613e8da28e4]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x182d9e)[0x7613e8e07d9e]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(PyObject_CallMethodObjArgs+0x101)[0x7613e8e07fe1]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x3e7951)[0x7613e906c951]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x3e86ab)[0x7613e906d6ab]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x3e965b)[0x7613e906e65b]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x3e9f3c)[0x7613e906ef3c]
/lib/x86_64-linux-gnu/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x4a5d)[0x7613e8da2f5d]
/mnt/shared/tmp-Buildings-0-nmt8avn4/Buildings/Resources/Library/linux64/libModelicaBuildingsPython_3_12.so(pythonExchangeValuesNoModelica+0xdbc)[0x7613e953158d]
Segmentation fault (core dumped)
139
```
However, sometimes, that command finishes without an error, producing
`LOG_SUCCESS       | info    | The simulation finished successfully.`

2026-08-04 23:23 UTC, JayHuLBL commented
The diagnostic with LLM is below:
```
Root cause of the intermittent segmentation fault

The crash happens inside the embedded‑CPython wrapper that all `TOUGH`‑based borefield models use to call Python:

`Resources/src/Utilities/IO/Python_3_12/pythonInterpreter.c` → `pythonExchangeValuesNoModelica()`

Two problems in this file combine to create a race condition that only shows up under certain OMC builds (such as the one baked into the `lbnlblum/ubuntu-2404-omc` Docker image):

1. **The Python interpreter is (re‑)initialized on every single call, not just once.**
   Unlike the Python 3.8 version of this file (`Resources/src/Utilities/IO/Python_3_8/pythonInterpreter.c`, which correctly guards initialization with `if (!Py_IsInitialized()) Py_Initialize();`), the Python 3.12 version unconditionally calls:
   ```c
   PyConfig_InitPythonConfig(&config);
   ...
   status = Py_InitializeFromConfig(&config);
   ...
   if (!Py_IsInitialized())      // always true here, so this check is dead code
       Py_Initialize();
   ```
   `Py_InitializeFromConfig()` is executed on *every* invocation of `doStep` (i.e., on every `sampleTrigger` event), even though the interpreter is already running. Repeated re‑initialization with a `PyConfig` (as opposed to the simple, idempotent `Py_Initialize()`) is not something CPython guarantees to be safe, and it manipulates global interpreter/runtime state (including `sys.path`, via the `strtok()` call performed in‑place on the persistently‑stored `ptrMemory->pythonPath` buffer) on every call.

2. **No GIL protection around the CPython C‑API calls.**
   The function calls `PyImport_Import`, `PyObject_GetAttrString`, `PyObject_CallObject`, etc. directly, without ever calling `PyGILState_Ensure()` / `PyGILState_Release()`. This implicitly assumes the function is only ever entered from a single native thread at a time.

The OpenModelica runtime, however, does not guarantee that external functions embedded in `when` clauses / the initialization system are only ever evaluated from one thread. Depending on how the runtime was built (this differs between the OMC binary bundled in the `lbnlblum/ubuntu-2404-omc` Docker image and a natively-installed OMC), the initialization/event system can evaluate the residual equations that contain the external call from more than one thread (e.g., for parallel/finite‑difference Jacobian evaluation during initialization, which is exactly where the log shows the crash occurring — right at/after "The initialization finished successfully"). When two threads enter `pythonExchangeValuesNoModelica` at (nearly) the same time:
- both may try to run `Py_InitializeFromConfig`/mutate `sys.path` concurrently, and/or
- both execute CPython bytecode via `PyObject_CallObject`/`_PyEval_EvalFrameDefault` concurrently without holding the GIL.

CPython's interpreter state and object allocator (`obmalloc`) are not thread‑safe without the GIL, so concurrent, unsynchronized access corrupts interpreter memory. The corruption doesn't crash deterministically — it depends on thread scheduling/timing.
```

2026-08-06 17:32 UTC, JayHuLBL commented
@mwetter It's ready to merge.

2026-08-06 20:25 UTC, mwetter commented
@JayHuLBL : Please also compile the binary on windows. The it is ready to merge.

2026-08-06 21:35 UTC, mwetter approved these changes

2026-08-10 23:20 UTC, merged