Maint 10.0.x Fix load computation in chiller and heat pump models
lbl-srg/modelica-buildings pull request #3880
Opened 2024-06-12 08:36 UTC by AntoineGautier

This addresses #3815.

2024-06-12 13:53 UTC, mwetter approved these changes

2024-06-12 13:55 UTC, mwetter requested changes
@AntoineGautier : looks good except that there should be an entry in the top-level release notes

2024-06-12 14:28 UTC, AntoineGautier commented
@mwetter Should it be under "Version 10.1.1" or "Version 10.0.0"?

2024-06-12 21:01 UTC, mwetter commented
> @mwetter Should it be under "Version 10.1.1" or "Version 10.0.0"?

It needs to be under 10.1.1 as this will be the version to be released.

2024-06-17 17:00 UTC, mwetter approved these changes

2024-06-17 17:00 UTC, merged